name: NStore CI

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  attestations: write
  
jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '10.x' ] #, '2.2.301', '3.0.100-preview9-014004' ]
        os: ['ubuntu-latest'] #['windows-latest', 'ubuntu-latest', 'macOS-latest']
    name: Build for .NET ${{ matrix.dotnet }}
    steps:
      # We want the build to continue not to block at the very first error
      # continue-on-error: true 
      
    - name: Checkout repository
      uses: actions/checkout@v1
    
    - name: Set up .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Set up .NET 10
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.x
         
    - name: Start SQL Server (MSSQL) Docker container
      run: docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=sqlPw3$secure' -e 'MSSQL_PID=Developer' -p 1433:1433 --name msssql -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu
      
    - name: Start MongoDB Docker container
      run: docker run -d -p 27017:27017 mongo
      
    - name: Dump SQL Server container logs
      run: docker logs msssql
      
    - name: Run build script (newbuild.ps1)
      shell: pwsh
      env:
        NSTORE_MONGODB: mongodb://localhost/nstore
        NSTORE_MSSQL: Server=localhost;user id=sa;password=sqlPw3$secure
      run: |
        ./newbuild.ps1 -nugetPublish $true -nugetApiKey ${{ secrets.NUGET_API_KEY }}

    - name: Generate artifact attestation (attest-build-provenance)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'artifacts/NuGet'
          
    - name: Upload NuGet packages artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: artifacts/NuGet
    
    - name: Upload Test results artifact (always)
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: TestResults
        path: TestResults

