name: 'Test Report'
on:
  workflow_run:
    workflows: ['SonarCloud']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: TestResults             # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: '*.trx'                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx              # Format of test results